# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82b5133ae1378dde6273166144fb8638004d1421763d35bf6b74b9acf3e5942587546eeff240be8848c3f1874dad4e3c7b0b40270fe749f8194ce83408d78587

test:
  secret_key_base: 3d8f83d4aecf8a1872dab1604afee4d126413271a6cdd12b1156839b989f877e48d8a8d81ce11f54b906c52c0a9d01787fee72d95564c2393a64438eaf32097c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
